#!/bin/sh

set -o errexit

. /etc/lsb-release

message() {
    msg=$1
    echo "$msg"
    echo "$msg" >> ~/stackful-node-summary.txt
}

rm -f ~/stackful-node-summary.txt

message "Checking if OS/Distro is supported..."

if [ "$DISTRIB_ID" != "Ubuntu" -o "$DISTRIB_RELEASE" != "12.04" ] ; then
    message "Unsupported OS/distro. Supported: Ubuntu 12.04"
    exit
fi

message "Installing prerequisite packages..."
DEBIAN_FRONTEND=noninteractive apt-get install --yes dialog git

STACK_REPO="https://github.com/stackful/stackful-node.git"
STACK_SOURCE="/tmp/stackful-node"

message "Fetching stack files from $STACK_REPO ..."
git clone "$STACK_REPO" "$STACK_SOURCE"
cd "$STACK_SOURCE"
git submodule update --init

message "Setting up Git deploy user..."
./bootstrap/install-git-repo


message "Installing Opscode Chef..."
curl -L https://www.opscode.com/chef/install.sh | bash

message "Finishing stack installation..."
GIT_USER=$(cat bootstrap/git_user.txt)
./run $GIT_USER

echo "INSTALLATION SUMMARY (also saved to ~/stackful-node-summary.txt):\n"
cat ~/stackful-node-summary.txt
